import type { NextPage } from "next";
import Head from "next/head";
import UploadForm from "../components/UploadForm";
import UploadList from "../components/UploadList";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Upload a file</h2>
        <br></br>

        <UploadForm />
        <br></br>
        <br></br>
        <h2 className={styles.title}>All uploads</h2>
        <br></br>
        <UploadList />
      </main>
    </div>
  );
};

export default Home;
