import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import FileInput from "../components/FileInput";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FileInput />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to File upload!</h1>
      </main>
    </div>
  );
};

export default Home;
